# Generated by Django 4.0.5 on 2022-06-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
