# Generated by Django 4.0.5 on 2022-07-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='desciption',
            new_name='description',
        ),
    ]
